-- ***************************************** --
-- *                                       * --
-- * trialの共通アカウントで選択テーブル   * --
-- *     insert                            * --
-- *     ver 1.0.0 20200822                * --
-- *                                       * --
-- ***************************************** --

-- csv_item_selections--
delete from attendance.csv_item_selections where account_id = 'TRIAL000';
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,1,1,'user_code','社員コード','社員コード','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,2,2,'user_name','氏名','氏名','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,3,0,'department','部署名','部署名','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,4,0,'employment','雇用形態名','雇用形態名','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,5,5,'total_working_status','出勤日数','出勤日数','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,6,6,'total_absence','欠勤日数','欠勤日数','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,7,7,'total_paid_holidays','有給休暇日数','有給休暇日数','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,8,8,'total_deemed','みなし日数','みなし日数','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,9,9,'total_public_damage','公傷日数','公傷日数','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,10,10,'total_congratulatory','慶弔日数','慶弔日数','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,11,0,'total_leave_early','早退日数','早退日数','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,12,0,'total_late','遅刻日数','遅刻日数','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,13,13,'total_holiday_kubun','特別休暇日数','特別休暇日数','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,14,14,'not_employment_working_hours','不就労時間','不就労時間','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,15,15,'overtime_hours','普通残業時間','普通残業時間','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,16,0,'off_hours_working_hours','時間外労働時間','時間外労働時間','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,17,17,'late_night_overtime_hours','深夜残業時間','深夜残業時間','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,18,18,'late_night_working_hours','深夜労働時間','夜勤手当','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,19,19,'legal_working_holiday_hours','法定休日労働時間','法定休日手当','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,20,20,'out_of_legal_working_holiday_hours','法定外休日労働時間','所定休日勤手当','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,21,0,'total_working_times','実働時間','実働時間','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,22,0,'regular_working_times','所定時間','所定労働時間','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,23,0,'out_of_regular_working_times','所定外時間','所定外労働時間','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,24,0,'legal_working_times','法定労働時間','法定労働時間','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,25,0,'out_of_legal_working_times','法定外労働時間','法定外労働時間','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,26,0,'public_going_out_hours','公用外出時間','公用外出時間','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,27,0,'missing_middle_hours','私用外出時間','私用外出時間','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,28,23,'total_substitute_holiday','代替休日日数','代休日数','0','systemuser','','2020/07/22 1:52:52',null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,29,24,'total_compensation_holiday','振替休日日数','振休日数','0','systemuser','','2020/07/22 1:52:52',null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',1,99,99,'title','タイトル','タイトル','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,1,1,'user_code','社員コード','社員コード','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,2,2,'workingdate','日付','日付','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,3,3,'attendance','出勤時刻','出勤時刻','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,4,4,'leaving','退勤時刻','退勤時刻','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,5,5,'public_going_out_hours','公用外出時間','公用外出時間','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,6,6,'missing_middle_hours','私用外出時間','私用外出時間','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,7,7,'remark_holiday_name','休暇','休暇','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',3,1,1,'working_date_name','日付','日付','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',3,2,2,'attendance_time','出勤時刻','出勤時刻','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',3,3,3,'leaving_time','退勤時刻','退勤時刻','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',3,4,4,'pcstart_time','PC起動時刻','PC起動時刻','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',3,5,5,'pcend_time','PC終了時刻','PC終了時刻','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',3,6,6,'difference_reason','差異の理由','差異の理由','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,1,1,'user_code','社員コード','社員コード（半角英数字10桁）','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,2,2,'department_name','部署名','部署名','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,3,3,'employment_name','雇用形態名','雇用形態名','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,4,4,'user_name','社員名','社員名（全角50文字以内）','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,5,5,'user_kana','社員カナ名','社員カナ名（半角30文字以内、全角15文字以内）','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,6,0,'official_position','役職','役職（全角50文字以内）','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,7,0,'apply_term_from','適用開始日','適用開始日','0','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,8,6,'kill_from_date','退職日','退職日','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,9,7,'working_timetable_name','タイムテーブル名','タイムテーブル名','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,10,8,'email','メールアドレス','メールアドレス','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,11,9,'mobile_email','モバイルメールアドレス','モバイルメールアドレス','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,12,10,'management','勤怠管理','勤怠管理（半角数字）','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',4,13,11,'role','権限','権限（半角数字）','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,1,1,'department_name','部署名','部署名','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,2,2,'employment_name','雇用形態名','雇用形態名','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,3,3,'user_name','氏名','氏名','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,4,4,'scheduled_results','予実績','','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,5,5,'day1','1','1','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,6,6,'day2','2','2','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,7,7,'day3','3','3','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,8,8,'day4','4','4','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,9,9,'day5','5','5','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,10,10,'day6','6','6','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,11,11,'day7','7','7','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,12,12,'day8','8','8','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,13,13,'day9','9','9','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,14,14,'day10','10','10','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,15,15,'day11','11','11','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,16,16,'day12','12','12','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,17,17,'day13','13','13','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,18,18,'day14','14','14','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,19,19,'day15','15','15','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,20,20,'day16','16','16','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,21,21,'day17','17','17','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,22,22,'day18','18','18','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,23,23,'day19','19','19','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,24,24,'day20','20','20','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,25,25,'day21','21','21','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,26,26,'day22','22','22','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,27,27,'day23','23','23','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,28,28,'day24','24','24','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,29,29,'day25','25','25','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,30,30,'day26','26','26','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,31,31,'day27','27','27','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,32,32,'day28','28','28','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,33,33,'day29','29','29','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,34,34,'day30','30','30','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,35,35,'day31','31','31','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,36,36,'regular_day_cnt','日勤','日勤','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,37,37,'night_day_cnt','夜勤','夜勤','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,38,38,'weekly_dayoff_cnt','週休振替','週休振替','1','systemuser','',now(),null,'0');
insert into attendance.csv_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',5,39,39,'paid_holiday_cnt','有給休暇','有給休暇','1','systemuser','',now(),null,'0');


-- feature_item_selections--
delete from attendance.feature_item_selections where account_id = 'TRIAL000';
insert into attendance.feature_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,value_select,description,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,1,1,'attendance_count','所定時間帯設定数','','1','出退勤打刻最大数','system',null,'2020/05/20 9:00:00',null,'0');
insert into attendance.feature_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,value_select,description,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,2,1,'half_holiday','半休自動設定','','0','半休設定時、出退勤の時刻を自動に設定するかどうか','system',null,'2020/05/20 9:00:00',null,'0');
insert into attendance.feature_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,value_select,description,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,3,1,'rest_count','休憩時間帯設定数','','5','休憩時間打刻最大数','system',null,'2020/05/20 9:00:00',null,'0');
insert into attendance.feature_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,value_select,description,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,4,1,'mode_list','レコードタイムモードリスト','','1','generalcodes=C005の選択リスト設定時の[use_free_item]の値','system',null,'2020/05/20 9:00:00',null,'0');
insert into attendance.feature_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,value_select,description,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,5,1,'early_time','早出時間集計','','0','1時間早出早退を通常通りとするかどうか','system',null,'2020/05/20 9:00:00',null,'0');
insert into attendance.feature_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,value_select,description,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,6,1,'select_clear','日付変更時の選択リストクリア','','1','検索条件で日付を変更した場合ユーザー情報に関する項目の選択リストをクリアするかどうか','system',null,'2020/05/20 9:00:00',null,'0');
insert into attendance.feature_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,value_select,description,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,7,1,'calendar_holiday_list','休暇区分選択リスト設定項目','','0','カレンダー設定に1日休暇以外の項目も選択リストに含めるか','system',null,'2020/05/20 9:00:00',null,'0');
insert into attendance.feature_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,value_select,description,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,8,1,'calc_list_allselect','日次月次集計選択リスト','','0','個人権限に選択リスト全従業員を含める','systemuser',null,'2020/08/13 8:59:59',null,'0');
insert into attendance.feature_item_selections(account_id,selection_code,item_code,item_seq,item_name,item_kanji_name,item_out_name,value_select,description,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,9,1,'account_id_valid','アカウントID有効','','1','アクセスにアカウントIDを含める','systemuser',null,'2020/08/13 9:00:06',null,'0');


-- menu_item_selections--
delete from attendance.menu_item_selections where account_id = 'TRIAL000';
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,1,'calc_block','集計','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,2,'daily','日次集計','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,3,'monthly','月次集計','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,4,'alert_block','警告通知','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,5,'daily_alert','日次警告通知','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,6,'monthly_alert','月次警告通知','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,7,'attendancelog_block','勤怠ログ','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,8,'store_attendancelog','勤怠ログ登録','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,9,'edit_attendancelog','勤怠ログ編集','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,10,'edit_block','編集','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,11,'create_shift_time','シフト編集','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,12,'edit_work_times','勤怠編集','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,13,'demand_block','申請機能','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,14,'demand','各種申請作成','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,15,'approval','各種申請承認','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,16,'confirm','承認者ルート設定','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,17,'setting_block','設定','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,18,'create_company_information','会社設定','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,19,'create_department','組織設定','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,20,'setting_calc','労働時間基本設定','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,21,'create_time_table','勤務帯時間設定','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,22,'setting_calendar','カレンダー設定','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,23,'edit_user','ユーザ情報設定','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,24,'operation_block','操作','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,25,'user_pass','パスワード変更','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,26,'file_download','ダウンロード','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,27,'edit_worktime_user','編集者表示','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,28,'edit_worktime_user_conditional','条件付き編集者表示','1','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,29,'TeamViewer','遠隔リモート','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,30,'account_admin','管理者画面接続説明書','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,31,'clientServer','クライアント版説明書','0','system','','2020/04/27 9:00:00',null,'0');
insert into attendance.menu_item_selections(account_id,selection_code,item_code,item_name,item_kanji_name,is_select,created_user,updated_user,created_at,updated_at,is_deleted) values ('TRIAL000',2,32,'setting_employment','雇用形態設定','0','systemuser','','2020/07/22 3:06:35',null,'0');


